### ISSUE TITLE
6-word solution?

### ISSUE THREAD

**Issue by Armavica** [alexandres/magicwordschallenge#2]
I found these 6 "words": `COMBO FATTY GRRRL SPUDS VENGE WHILK` (all in `words_full.txt`) which are a solution according to my simulator.
However, your `check.cpp` does not agree. But if print the contents of `possible_words` at line 246, I get `QUITE` and `QUIET`, which should be distinguished given the 6 words above (by `FATTY` and by `VENGE`). Is there something that I am doing wrong?

**Comment by alexandres** [comment]
Your solution looks right to me! That is amazing news. 🙌 🙌 🙌   

I believe the issue is in the simulator I used. 

The issue is caused by:

```
COMBO FATTY GRRRL SPUDS VENGE WHILK
Error: multiple possible words for hidden word QUIET
QUIET
QUITE
```

I ran a quick test:

```cpp
auto guess = FiveLetterWord("VENGE");
auto hidden = FiveLetterWord("QUIET");
auto conflict = FiveLetterWord("QUITE");
auto hint = evaluate_guess(guess, hidden);
std::cerr << "Hint: " << hint.to_squares() << std::endl;
auto is_possible = IsWordPossible(hint, guess, conflict);
std::cerr << "Is possible: " << is_possible << std::endl;
```

Outputs

```
Hint: xYxxx
Is possible: 1
```

Does your simulator return the same hint? The hint seems to correctly eliminate QUITE since there's an x at the last position, so the bug must be in the `IsWordPossible` function.

**Comment by Armavica** [comment]
Yes, I have the same hint when I compare the guess `VENGE` to the hidden word `QUIET`: `01000`.

**Comment by alexandres** [comment]
Can you share your `IsWordPossible` code here to replace https://github.com/alexandres/magicwordschallenge/blob/main/check.cpp#L134 ?

**Comment by Armavica** [comment]
I don't really have this function in my code, but wouldn't it simpler to compare `hint` and `evaluate_guess(guess, word)`? Or am I missing something?

**Comment by alexandres** [comment]
In your code, how you eliminate candidate hidden words given a guess and its feedback?

**Comment by Armavica** [comment]
I don't eliminate words, I just check that all the feedbacks are different, for example (simplified code):
```python
guesses = ['COMBO', 'FATTY', 'GRRRL', 'SPUDS', 'VENGE', 'WHILK']
feedbacks = [[compare(guess, hidden) for guess in guesses] for hidden in hidden_words]
# now I can check that all the lines of `feedbacks` are different
nb_collisions = len(feedbacks) - len(set(feedbacks))
# if `nb_collisions == 0`, then `guesses` is a solution
```

**Comment by alexandres** [comment]
I think I understand. You have a function that given a set of guesses and a
hidden word, returns a unique set of feedbacks. You require that this
mapping be one-to-one.

To infer a hidden word, you collect feedbacks using the fixed set of
guesses and use the mapping to find the associated hidden word.

I love it!

**Comment by Armavica** [comment]
Yes, checking that N guesses are an offline solution is equivalent to checking that every feedback given by the hidden words is unique (if you combine the N feedbacks), so that it is possible to distinguish every hidden word.

**Comment by alexandres** [comment]
Awesome. I will correct the check program usinf your idea and update the
README to show that 6 word solution exists. Congratulations! 💪🏻💪🏻

What seemed impossible might just be possible.

**Comment by Armavica** [comment]
Great :) Looking for 5 now :)

**Comment by alexandres** [comment]
[Updated code and README](https://github.com/alexandres/magicwordschallenge/commit/312cc07436a4ae904998eeb8b345cdfc7393ef53) with your algorithm and solution! :)

**Comment by xanthe-cat** [comment]
Hello Alexandre and Virgile,

I’m the creator of a (notorious?) Wordle knock-off that uses a slightly larger hidden wordlist than the 2,315 pre-NYT Wordle: it uses 2,686 words in total, including about 190 words that Josh Wardle initially had included in the game as of last October, and subsequently chose to remove.

This should make it more difficult to find sets of magic words: for example, none of the 8, 7, or 6 word solutions in the README.md satisfy the check program when run against the 2,686 wordlist (they have 1, 2, and 10 conflicts respectively). However, in doing somewhere between a dozen and two dozen runs of the 8-word version of magicwords, I found 7 different 8 word solutions for the larger set, so I continued running it until I obtained an 8th. Here they are:

8: ADDER BURAN CAHOW FELLA KNOSP MATTE RITZY VLOGS
8: AHULL ATTAR CHINK FAZES MERGE NODDY PROVE UPBOW
8: APPEL CRWTH DAZED DEFOG MURKY SNIBS TABLE VEGAS
8: ARGON CWTCH DAZED FLYPE JUNKS MELBA RORAL VIOLD
8: CAROB FELLY MIDDY PLOTS SAVER THUNK WIMPS ZIGAN
8: CROON DRUID FUSEL MAWKY PLEBE RIDGY SHAVE TARPS
8: CAMAN DEWED FOOTS PIRNS SNABS THILK VOUGE XYLYL
8: CURLI DOWDS GLOBE MUTCH PAVAN REFEL SPIKS TANGY

Each of these satisfies both the 2,686 wordlist and the 2,315 Wordle wordlist – which is as you would expect to always be the case, when one list is a strict subset of the other, as here. Since it is hardly impossible that the NYT might change the wordlist at any time, it’s not out of the question that the current best magic words discovered might be invalidated by a subsequent version of the game, while magic words discovered training on a larger set of hidden words might be more resilient to such a change.

Anyway, I’ve gotten fairly close to a 7-word solution for the 2,686 word set a couple of times after running magicwords for several days. I’ve noticed it’s fairly uncommon for a search to improve dramatically the more iterations that have been gone through – usually the current solution will converge quickly towards a low number of conflicts within the first 10,000 to 20,000 iterations, but it won’t improve greatly beyond that point. One search only got down to 3 conflicts after 700,000 iterations, while a different search reduced to just 2 conflict after 1,100 iterations, and then stubbornly sat there for 250,000 more iterations. Et cetera.

The most promising 7-word set I’ve discovered converged down to a single conflict fairly rapidly:
7: CADDY FLOOR MUNGE PLANK SWEEP TILTH VERBS (1 conflict)

There are numerous alternative sets I can find shuffling letters around from one word to another without reducing the number of conflicts by that last number, e.g.:
7: CADDY FREER MUNGE PLANK SWOOP TILTH VERBS (also 1 conflict)
7: CHEER FLANK MUNGE PADDY SWOOP TILTH VERBS (1)
7: CHEER FLANK MUNGE SPOOL TILTH VERBS WADDY (1)
7: CLANK FLEER MUNGE SPOOL TILTH VERBS WADDY (1)
7: CREEL FADDY MUNGE PLANK SWOOP TILTH VERBS (1)

I’m wondering, since magicwords obviously begins somewhat randomly and then looks to refine the current set of words, whether it instead could be directed to investigate one or more candidate words?

I also found it useful to slightly modify the check.cpp code to make the output a little more verbose and to print out the number of conflicts, which only needed an additional line and changes to the lines above and below.

```
        auto is_solution = conflicts(solution);
        auto text = is_solution == 0 ? "These magic words solve Wordle, conflicts = " : "These words do not solve Wordle, conflicts = ";
        std::cerr << text << is_solution << std::endl;

```

**Comment by alexandres** [comment]
Hi @xanthe-cat ! Sorry for the late reply. `magicwords.cpp` implements a very basic [genetic algorithm](https://en.wikipedia.org/wiki/Genetic_algorithm). Your proposed "could be directed to investigate one or more candidate words" solution sounds like [simmulated annealing](https://en.wikipedia.org/wiki/Simulated_annealing) or [hill climbing](https://en.wikipedia.org/wiki/Hill_climbing). Trying both on this problem could be a fun exercise. You can also try reaching out to @Armavica to see if he'll share his code with you. 

Good luck!
